FROM debian:stretch-slim

# 2020-12-06版より後
LABEL maintainer="Satoshi Takahashi <muzudho1@gmail.com>"
# 2020-12-06版以前
LABEL original_maintainer="Daigo Moriwaki <daigo@debian.org>"

RUN apt-get update && apt-get install -y \
        ca-certificates \
        apt-utils \
        ruby ruby-gsl \
        # 以降、デバッグでよく使うものを追加（＾～＾）本番では要らないぜ（＾～＾）
        curl \
        iproute2 \
        vim


ENV EVENT local
# Test
ENV PORT 4000
ENV MAX_IDENTIFIER 32

# １階層目にログ・ディレクトリを置きます
WORKDIR /logs

# １階層目にshogi-serverディレクトリを置きます
WORKDIR /shogi-server

RUN gem install rgl

COPY . ./

EXPOSE $PORT

# CMD で１行で書くと見づらいのでファイルに分けたぜ（＾～＾）
ENTRYPOINT ["./docker-entrypoint.sh"]
